export type User = { id: string; email: string; name: string; role: "platform_admin" | "merchant_admin" | "merchant_operator"; merchantId: string | null };
export type Merchant = { id: string; name: string; status: string };
export type Conversation = { id: string; merchantId: string; countryId: string; countryCode: string; countryName: string; customerPhone: string; a2cAccountPhone: string; nickname: string; language: string; stage: string; flowStep?: string; extractedPhone: string; extractedTelegram: string; extractedWhatsApp: string; status: string; handoffStatus: string; unreadCount: number; pinnedAt?: string; updatedAt?: string };
export type Customer = { id: number; merchantId: string; countryId: string; countryCode: string; countryName: string; customerKey: string; nickname: string; firstA2CAccountPhone: string; lastA2CAccountPhone: string; language: string; stage: string; extractedPhone: string; extractedTelegram: string; extractedWhatsApp: string; status: string; conversationCount: number; lastConversationId: string; firstSeenAt: string; lastSeenAt: string };
export type Sample = { id: number; customerMessage: string; standardReply: string; stage: string; intent: string; language: string; keywords: string; priority: number; enabled?: boolean };
export type Knowledge = { id: number; merchantId: string; countryId?: string; type: string; title: string; content: string; language: string; priority: number; enabled: boolean };
export type CustomerMemory = { id: number; summary: string; facts: Record<string, unknown>; operatorNotes: string; updatedAt: string };
export type TrainingMaterial = { id: number; merchantId: string; sourceType: string; filename: string; status: string; itemCount: number; sampleCount: number; knowledgeCount: number; warnings: string[]; createdAt: string; rawText?: string };
export type TrainingMaterialItem = { id: number; kind: string; title: string; content: string; intent: string; stage: string; language: string; enabled: boolean };
export type A2CAccount = { id: number; merchantId: string; countryId: string; countryCode: string; countryName: string; defaultLanguage: string; apiPhone: string; wabaId: string; status: number; numberStatus: number; qualityRating: number; messagingLimit: number; verifiedName: string; enabled: boolean; syncedAt: string };
export type InviteCode = { id: number; merchantId: string; countryId: string; countryName: string; a2cAccountId: number; a2cAccountPhone: string; code: string; registerUrl: string; status: string; assignedCustomerKey: string; assignedConversationId: string; platformAccount: string; assignedAt: string; usedAt: string; createdAt: string; updatedAt: string };
export type MerchantCountry = { id: string; merchantId: string; code: string; name: string; defaultLanguage: string; platformRegisterUrl: string; tgRegisterGuideUrl: string; requirePlatformAccount: boolean; requirePhone: boolean; requireTelegram: boolean; requireWhatsApp: boolean; status: string };
export type ScriptFlow = { id: number; merchantId: string; countryId: string; countryName: string; name: string; status: string; active: boolean; version: number; sourceFilename: string; stepCount: number; createdAt: string; updatedAt: string };
export type ScriptFlowStep = { id: number; flowId: number; flowCode: string; flowName: string; flowStep: string; goal: string; triggerCondition: string; customerExpressions: string; standardReply: string; collectInfo: string; sendLink: boolean; sendInvite: boolean; nextCondition: string; nextFlowCode: string; nextFlowStep: string; forbidden: string; notes: string; sortOrder: number; enabled: boolean };
export type ScriptFlowVersion = { id: number; flowId: number; version: number; note: string; createdBy: string; createdAt: string };
export type ScriptFlowDetail = { flow: ScriptFlow; steps: ScriptFlowStep[]; versions?: ScriptFlowVersion[] };
export type IntentLearningEvent = { id: number; merchantId: string; countryId: string; conversationId: string; messageId: number | null; candidateKey: string; suggestedIntent: string; displayName: string; description: string; customerText: string; language: string; detectedIntent: string; inferredIntent: string; contextualIntent: string; flowStep: string; status: "candidate" | "reviewed" | "ignored" | "promoted"; occurrenceCount: number; examples: Array<Record<string, unknown>>; lastSeenAt: string; createdAt: string; updatedAt: string };
export type UnreadSummary = { a2cAccountPhone: string; unreadCount: number; conversations: Array<{ conversationId: string; customerPhone: string; unreadCount: number }> };
export type ChatMessage = { id: number; direction: string; content: string; msgType: string; language: string; intent: string; createdAt: string; rawPayload?: { originalContent?: string; translatedContent?: string; targetLanguage?: string; translationStatus?: "translated" | "skipped" | "failed"; translationError?: string; operatorTranslatedContent?: string; operatorTranslationTargetLanguage?: string; operatorTranslationStatus?: "translated" | "skipped" | "failed"; operatorTranslationError?: string; manual?: boolean; replyMode?: "strict_flow" | "ai" | "gemini" | "fallback" | "manual"; strictFlow?: boolean; strictFlowEnabled?: boolean; strictFlowStep?: string; samples?: number[]; trainingMaterials?: number[]; a2cSendStatus?: string; a2cSendError?: string } };
export type AgentProfile = { merchantId: string; agentName: string; roleDefinition: string; toneStyle: string; coreGoal: string; mustFollow: string; forbidden: string; uncertaintyPolicy: string; handoffPolicy: string; enabled: boolean; updatedAt: string };
export type ConversationReviewItem = { id: number; reviewId: number; itemType: "sample" | "knowledge"; title: string; content: string; status: "candidate" | "applied" | "ignored"; appliedTargetType: string; appliedTargetId: string };
export type ConversationReview = { id: number; score: number; goalCompleted: boolean; summary: string; mainConcerns: string[]; mistakes: string[]; goodReplies: string[]; suggestedSamples: Array<Record<string, unknown>>; suggestedKnowledge: Array<Record<string, unknown>>; improvementActions: string[]; status: string; updatedAt: string };
export type ConversationReviewResponse = { review: ConversationReview | null; items: ConversationReviewItem[] };
export type SimulatorResponse = { status: string; conversation?: Conversation; rows: ChatMessage[] };
export type ConfigCheck = { key: string; label: string; ok: boolean; status: "ok" | "missing" | "error" | "waiting"; detail: string };
export type Filters = Record<string, string>;
export type Toast = { id: number; type: "success" | "error" | "info"; title: string; detail?: string };
export type AiCallStats = {
  totalCalls: number;
  successCalls: number;
  errorCalls: number;
  successRate: number;
  averageDurationMs: number;
  availableProviders: string[];
  byType: Array<{ taskType: string; totalCalls: number; successCalls: number; errorCalls: number; successRate: number; averageDurationMs: number }>;
  byProvider: Array<{ provider: string; totalCalls: number; successCalls: number; errorCalls: number; successRate: number; averageDurationMs: number }>;
  byTypeDetails: Array<{ taskType: string; provider: string; model: string; totalCalls: number; successCalls: number; errorCalls: number; successRate: number; averageDurationMs: number; lastCalledAt: string }>;
  byError: Array<{ taskType: string; provider: string; model: string; errorMessage: string; httpStatus: number | null; requestSummary: string; responseSummary: string; errorCalls: number; lastFailedAt: string }>;
};
